version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - DELIVERY_SERVICE_URL=http://delivery-service:3004
    networks:
      - ctse-network
    depends_on:
      - auth-service
      - product-service
      - order-service
      - delivery-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb+srv://anjana2:anjana@cluster0.rg6ebmf.mongodb.net/auth_db
      - JWT_SECRET=supersecretjwtkey_ctse
      - ORDER_SERVICE_URL=http://order-service:3003
    networks:
      - ctse-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb+srv://anjana2:anjana@cluster0.rg6ebmf.mongodb.net/product_db
      - JWT_SECRET=supersecretjwtkey_ctse
      - AUTH_SERVICE_URL=http://auth-service:3001
    networks:
      - ctse-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb+srv://anjana2:anjana@cluster0.rg6ebmf.mongodb.net/order_db
      - JWT_SECRET=supersecretjwtkey_ctse
      - PRODUCT_SERVICE_URL=http://product-service:3002
    networks:
      - ctse-network

  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGO_URI=mongodb+srv://anjana2:anjana@cluster0.rg6ebmf.mongodb.net/delivery_db
      - JWT_SECRET=supersecretjwtkey_ctse
      - ORDER_SERVICE_URL=http://order-service:3003
    networks:
      - ctse-network

networks:
  ctse-network:
    driver: bridge
