apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: ctse-app
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: delivery-service
          image: praveen1214/delivery-service:8c1e16c
          imagePullPolicy: Always
          ports:
            - containerPort: 3304
          env:
            - name: PORT
              value: "3304"
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: ORDER_SERVICE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: AUTH_SERVICE_URL
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: CORS_ORIGIN
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: NODE_ENV
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ctse-secrets
                  key: DELIVERY_MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ctse-secrets
                  key: JWT_SECRET
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ctse-secrets
                  key: INTERNAL_SERVICE_TOKEN
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3304
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3304
            initialDelaySeconds: 5
            periodSeconds: 10
