apiVersion: v1
kind: Secret
metadata:
  name: ctse-secrets
  namespace: ctse-app
  labels:
    app: ctse
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  INTERNAL_SERVICE_TOKEN: "${INTERNAL_SERVICE_TOKEN}"
  AUTH_MONGO_URI: "${AUTH_MONGO_URI}"
  PRODUCT_MONGO_URI: "${PRODUCT_MONGO_URI}"
  ORDER_MONGO_URI: "${ORDER_MONGO_URI}"
  DELIVERY_MONGO_URI: "${DELIVERY_MONGO_URI}"
