# ──────────────────────────────────────────────────────────────────────────────
# TEMPLATE – DO NOT commit actual values to Git.
# Copy this file, fill in real values, then apply:
#   kubectl apply -f k8s/secrets.yaml
# ──────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: ctse-secrets
  namespace: ctse-app
  labels:
    app: ctse
type: Opaque
stringData:
  JWT_SECRET: "ctse_jwt"
  AUTH_MONGO_URI: "mongodb+srv://anjana2:anjana@cluster0.rg6ebmf.mongodb.net/CTSE_auth_db"
  PRODUCT_MONGO_URI: "mongodb+srv://anjana2:anjana@cluster0.rg6ebmf.mongodb.net/CTSE_product_db"
  ORDER_MONGO_URI: "mongodb+srv://anjana2:anjana@cluster0.rg6ebmf.mongodb.net/CTSE_order_db"
  DELIVERY_MONGO_URI: "mongodb+srv://anjana2:anjana@cluster0.rg6ebmf.mongodb.net/CTSE_delivery_db"
