apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ctse-app
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: api-gateway
          image: praveen1214/api-gateway:8c1e16c
          imagePullPolicy: Always
          ports:
            - containerPort: 3300
          env:
            - name: PORT
              value: "3300"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: AUTH_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: ORDER_SERVICE_URL
            - name: DELIVERY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: DELIVERY_SERVICE_URL
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: ctse-config
                  key: CORS_ORIGIN
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3300
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3300
            initialDelaySeconds: 5
            periodSeconds: 10
